// =============================================================================
//  maoni_pages.dart  -  Kubadilishana (EssTransfer) admin panel
//  "Maoni" (feedback inbox + chat). Single file, ready to drop in.
//
//  Dependencies (pubspec.yaml):
//    flutter_tabler_icons: ^1.43.0
//  Requires Flutter 3.10+ (Dart 3).
//
//  Pieces:
//    MaoniInboxPage   - list of conversations (page BODY: the app shell already
//                       has the top bar, drawer and bottom navigation).
//    MaoniChatPage    - full-screen chat with ONE person.
//    MaoniRepository  - the ONLY thing you connect to your backend.
//    InMemoryMaoniRepository - demo implementation (for testing the UI).
//
//  Usage:
//    MaoniInboxPage(repo: myRepository)
//
//  This file matches the approved mockups EXACTLY (white background, green
//  accents, swipe-to-reply, quote preview, live updates, auto-scroll).
//  Do not restyle it.
//
//  THE THREE RULES THAT FIX THE OLD BUGS (see MAELEZO_MAONI.md):
//    1. One conversation per PERSON (never one per message).
//    2. A message is identified by its id (and clientId while sending), so it
//       can never be shown twice ("sawa sawa").
//    3. The chat listens to a live stream, so new messages appear while the
//       chat is open.
// =============================================================================

import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_tabler_icons/flutter_tabler_icons.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../services/api_service.dart';
import '../../services/websocket_service.dart';
import '../../widgets/app_toast.dart' show AppToast, friendlyError;

// ----------------------------------------------------------------------------
// Colors (from the approved mockup)
// ----------------------------------------------------------------------------
class _C {
  // Ink/neutral — rangi za herufi tu, HAKUNA bluu kwenye mandhari.
  static const ink = Color(0xFF141A26);
  static const title = Color(0xFF141A26);
  static const muted = Color(0xFF8A94A6);
  static const muted2 = Color(0xFF8690A2);
  // Neutral safi — LAINI ZA WHATSAPP (siyo bluu/kijivu cha kina).
  static const field = Color(0xFFF7F8FA);
  static const line = Color(0xFFD9DDE1);
  static const border = Color(0xFFEDEFF2);
  static const green = Color(0xFF075E54);
  static const greenFg = Color(0xFF0A6C48);
  static const greenBg = Color(0xFFF0E9E1);
  static const avatarBg = Color(0xFFE7E0D8);
  static const quoteIn = Color(0x14075E54);
  static const quoteOut = Color(0x1F075E54);
  static const tick = Color(0xFF8696A0);
  // Nukuu ya jina/dhana (quote author/text) — nyeusi-pedestrian, siyo bluu.
  static const quoteName = Color(0xFF075E54);
  static const sendOff = Color(0xFFC9D4CE);
  static const red = Color(0xFFD83A3A);
  static const redBg = Color(0xFFFDECEC);
  static const hint = Color(0xFF8A94A6);
  // Interactive za nyuma (bar ya kujibu + kitufe cha vuta) — LAZIMA zinabaki
  // kijivu-safi kwenye background nyeupe (siyo bluu). Kijani hutumika kwenye
  // jina la mtangazaji tu kwenye quote.
  static const replyBar = Color(0xFFF2EFEA); // WhatsApp incoming-quote tint
  static const replyIconBg = Color(0xFFEFF1F3);
  static const chipText = Color(0xFF3B4451);
}

// ----------------------------------------------------------------------------
// Models
// ----------------------------------------------------------------------------
enum MsgStatus { sending, sent, delivered, read, failed }

class ReplyRef {
  final String messageId;
  final String senderName;
  final String text;
  const ReplyRef(this.messageId, this.senderName, this.text);
}

class ChatMessage {
  /// Server id. For a message that is still being sent this may be a temporary
  /// value; the real message from the backend replaces it (matched by clientId).
  final String id;

  /// Id generated by the app when sending. The backend MUST echo it back so the
  /// app can replace the local copy instead of showing the message twice.
  final String? clientId;
  final String userId;
  final bool fromAdmin;
  final String text;
  final DateTime time;
  final MsgStatus status;
  final ReplyRef? replyTo;

  const ChatMessage({
    required this.id,
    this.clientId,
    required this.userId,
    required this.fromAdmin,
    required this.text,
    required this.time,
    this.status = MsgStatus.sent,
    this.replyTo,
  });

  ChatMessage copyWith({MsgStatus? status}) => ChatMessage(
        id: id,
        clientId: clientId,
        userId: userId,
        fromAdmin: fromAdmin,
        text: text,
        time: time,
        status: status ?? this.status,
        replyTo: replyTo,
      );
}

/// ONE row per person in the inbox.
class Conversation {
  final String userId;
  final String name;
  final String phone;
  final String lastText;
  final DateTime lastTime;
  final bool lastFromAdmin;
  final MsgStatus lastStatus;

  /// Number of messages from this person after the admin's last reply.
  /// 0 = nothing waiting. Replying clears it (opening the chat does NOT).
  final int awaiting;

  const Conversation({
    required this.userId,
    required this.name,
    required this.phone,
    required this.lastText,
    required this.lastTime,
    required this.lastFromAdmin,
    this.lastStatus = MsgStatus.delivered,
    this.awaiting = 0,
  });
}

// ----------------------------------------------------------------------------
// Repository: connect THIS to your backend (REST + websocket / Firestore / ...)
// ----------------------------------------------------------------------------
abstract class MaoniRepository {
  /// Live list of conversations, ONE per person, newest first.
  Stream<List<Conversation>> watchConversations();

  /// Live list of ALL messages with one person, oldest first. Must emit the
  /// current list immediately and again whenever anything changes (new
  /// incoming message, your reply confirmed, status changed).
  Stream<List<ChatMessage>> watchMessages(String userId);

  /// Send an admin reply. The backend must store it once and echo [clientId]
  /// on the saved message (so the app can match it).
  Future<void> sendReply({
    required String userId,
    required String text,
    required String clientId,
    String? replyToMessageId,
  });

  Future<void> deleteConversation(String userId);

  /// Optional: header button "mark all seen". Does not change `awaiting`.
  Future<void> markAllSeen();
}

// ----------------------------------------------------------------------------
// Inbox page
// ----------------------------------------------------------------------------
enum _InboxFilter { all, waiting, answered }

class MaoniInboxPage extends StatefulWidget {
  final MaoniRepository repo;

  /// Called when the call button is tapped inside a chat (url_launcher: tel:).
  final void Function(String phone)? onCall;
  const MaoniInboxPage({super.key, required this.repo, this.onCall});

  @override
  State<MaoniInboxPage> createState() => _MaoniInboxPageState();
}

class _MaoniInboxPageState extends State<MaoniInboxPage> {
  _InboxFilter _filter = _InboxFilter.all;
  String _query = '';

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: StreamBuilder<List<Conversation>>(
        stream: widget.repo.watchConversations(),
        builder: (context, snap) {
          final all = snap.data ?? const <Conversation>[];
          final q = _query.toLowerCase();
          final searched = all
              .where((c) =>
                  q.isEmpty ||
                  c.name.toLowerCase().contains(q) ||
                  c.phone.contains(q) ||
                  c.lastText.toLowerCase().contains(q))
              .toList();
          final waitingCount = searched.where((c) => c.awaiting > 0).length;
          final shown = searched.where((c) {
            switch (_filter) {
              case _InboxFilter.all:
                return true;
              case _InboxFilter.waiting:
                return c.awaiting > 0;
              case _InboxFilter.answered:
                return c.awaiting == 0;
            }
          }).toList();
          final waiting = all.where((c) => c.awaiting > 0).toList();

          return ListView(
            padding: const EdgeInsets.only(top: 16, bottom: 24),
            children: [
              _header(),
              _search(),
              _chips(searched.length, waitingCount),
              if (waiting.isNotEmpty) _waitingRow(waiting),
              if (snap.connectionState == ConnectionState.waiting && all.isEmpty)
                const Padding(
                  padding: EdgeInsets.all(40),
                  child: Center(child: CircularProgressIndicator()),
                )
              else if (shown.isEmpty)
                const Padding(
                  padding: EdgeInsets.all(30),
                  child: Center(
                    child: Text('Hakuna matokeo',
                        style: TextStyle(color: _C.muted2, fontSize: 14)),
                  ),
                )
              else
                for (final c in shown) _row(c),
            ],
          );
        },
      ),
    );
  }

  Widget _header() => Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        child: Row(
          children: [
            const Text('Maoni',
                style: TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.w500,
                    letterSpacing: -.5,
                    color: _C.title)),
            const SizedBox(width: 10),
            const Padding(
              padding: EdgeInsets.only(top: 6),
              child: CircleAvatar(radius: 4.5, backgroundColor: _C.green),
            ),
            const Spacer(),
            _Press(
              onTap: () => widget.repo.markAllSeen(),
              child: Container(
                width: 42,
                height: 42,
                decoration: const BoxDecoration(
                    color: _C.field, shape: BoxShape.circle),
                child: const Icon(TablerIcons.checks, size: 20, color: _C.tick),
              ),
            ),
          ],
        ),
      );

  Widget _search() => Padding(
        padding: const EdgeInsets.fromLTRB(16, 14, 16, 12),
        child: SizedBox(
          height: 46,
          child: TextField(
            onChanged: (v) => setState(() => _query = v.trim()),
            style: const TextStyle(fontSize: 15, color: _C.ink),
            decoration: InputDecoration(
              hintText: 'Tafuta jina, namba au ujumbe',
              hintStyle: const TextStyle(color: Color(0xFF8A94A6), fontSize: 15),
              filled: true,
              fillColor: _C.field,
              contentPadding: const EdgeInsets.symmetric(horizontal: 16),
              suffixIcon:
                  const Icon(TablerIcons.search, size: 20, color: _C.muted),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(16),
                borderSide: BorderSide.none,
              ),
            ),
          ),
        ),
      );

  Widget _chips(int total, int waiting) {
    Widget chip(_InboxFilter f, String label, int count) {
      final on = _filter == f;
      return GestureDetector(
        onTap: () => setState(() => _filter = f),
        child: Container(
          height: 36,
          padding: const EdgeInsets.symmetric(horizontal: 14),
          decoration: BoxDecoration(
            color: on ? _C.greenBg : _C.field,
            borderRadius: BorderRadius.circular(18),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(label,
                  style: TextStyle(
                      fontSize: 14,
                      fontWeight: on ? FontWeight.w500 : FontWeight.w400,
                      color: on ? _C.greenFg : _C.chipText)),
              const SizedBox(width: 7),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 1),
                decoration: BoxDecoration(
                  color: on ? _C.green : Colors.white,
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Text('$count',
                    style: TextStyle(
                        fontSize: 12.5, color: on ? Colors.white : _C.chipText)),
              ),
            ],
          ),
        ),
      );
    }

    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 0, 16, 14),
      child: Wrap(
        spacing: 8,
        runSpacing: 8,
        children: [
          chip(_InboxFilter.all, 'Zote', total),
          chip(_InboxFilter.waiting, 'Hayajajibiwa', waiting),
          chip(_InboxFilter.answered, 'Yamejibiwa', total - waiting),
        ],
      ),
    );
  }

  Widget _waitingRow(List<Conversation> waiting) => Container(
        padding: const EdgeInsets.fromLTRB(16, 2, 16, 14),
        decoration: const BoxDecoration(
          border: Border(bottom: BorderSide(color: _C.line)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Wanaosubiri jibu lako',
                style: TextStyle(fontSize: 13, color: _C.muted2)),
            const SizedBox(height: 10),
            SizedBox(
              height: 92,
              child: ListView.separated(
                scrollDirection: Axis.horizontal,
                itemCount: waiting.length,
                separatorBuilder: (_, __) => const SizedBox(width: 16),
                itemBuilder: (_, i) {
                  final c = waiting[i];
                  return GestureDetector(
                    onTap: () => _open(c),
                    child: SizedBox(
                      width: 64,
                      child: Column(
                        children: [
                          Stack(
                            clipBehavior: Clip.none,
                            children: [
                              Container(
                                width: 58,
                                height: 58,
                                alignment: Alignment.center,
                                decoration: BoxDecoration(
                                  color: _C.avatarBg,
                                  shape: BoxShape.circle,
                                  border:
                                      Border.all(color: _C.green, width: 2.5),
                                ),
                                child: Text(_initial(c.name),
                                    style: const TextStyle(
                                        fontSize: 20,
                                        fontWeight: FontWeight.w500,
                                        color: _C.ink)),
                              ),
                              Positioned(
                                top: -4,
                                right: -4,
                                child: _CountBadge(c.awaiting, border: true),
                              ),
                            ],
                          ),
                          const SizedBox(height: 6),
                          Text(_firstName(c.name),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(
                                  fontSize: 12.5, color: _C.chipText)),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      );

  Widget _row(Conversation c) {
    final unread = c.awaiting > 0;
    return InkWell(
      onTap: () => _open(c),
      child: Padding(
        padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _Avatar(c.name, size: 54, fontSize: 20),
            const SizedBox(width: 14),
            Expanded(
              child: Container(
                padding: const EdgeInsets.only(bottom: 12),
                decoration: const BoxDecoration(
                  border: Border(bottom: BorderSide(color: _C.line)),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(children: [
                      Expanded(
                        child: Text(c.name,
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                            style: const TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.w500,
                                color: _C.ink)),
                      ),
                      const SizedBox(width: 8),
                      Text(_listTime(c.lastTime),
                          style: TextStyle(
                              fontSize: 12.5,
                              fontWeight:
                                  unread ? FontWeight.w500 : FontWeight.w400,
                              color: unread ? _C.green : _C.muted2)),
                    ]),
                    const SizedBox(height: 3),
                    Row(children: [
                      if (c.lastFromAdmin) ...[
                        _Ticks(c.lastStatus, size: 17),
                        const SizedBox(width: 4),
                      ],
                      Expanded(
                        child: Text(c.lastText,
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                            style: TextStyle(
                                fontSize: 14.5,
                                fontWeight:
                                    unread ? FontWeight.w500 : FontWeight.w400,
                                color: unread ? _C.ink : _C.muted)),
                      ),
                      if (unread) ...[
                        const SizedBox(width: 8),
                        _CountBadge(c.awaiting),
                      ],
                    ]),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _open(Conversation c) {
    Navigator.of(context).push(MaterialPageRoute(
      builder: (_) => MaoniChatPage(
        repo: widget.repo,
        conversation: c,
        onCall: widget.onCall,
      ),
    ));
  }
}

// ----------------------------------------------------------------------------
// Chat controller: merges server messages + pending local ones WITHOUT dupes
// ----------------------------------------------------------------------------
class ChatController extends ChangeNotifier {
  final MaoniRepository repo;
  final String userId;
  final String userName;

  List<ChatMessage> _server = const [];
  final List<ChatMessage> _pending = [];
  StreamSubscription<List<ChatMessage>>? _sub;
  ChatMessage? replyTo;
  bool atBottom = true;
  int newWhileAway = 0;
  bool loaded = false;

  ChatController({
    required this.repo,
    required this.userId,
    required this.userName,
  }) {
    _sub = repo.watchMessages(userId).listen(_onServer);
  }

  /// Final list shown on screen (oldest first). A pending local message is
  /// hidden as soon as the backend echo with the same clientId arrives.
  List<ChatMessage> get messages {
    final echoed = <String>{
      for (final m in _server)
        if (m.clientId != null) m.clientId!,
    };
    final seenIds = <String>{};
    final out = <ChatMessage>[];
    for (final m in _server) {
      if (seenIds.add(m.id)) out.add(m); // never show the same id twice
    }
    for (final p in _pending) {
      if (!echoed.contains(p.clientId)) out.add(p);
    }
    out.sort((a, b) => a.time.compareTo(b.time));
    return out;
  }

  void _onServer(List<ChatMessage> list) {
    final prevIncoming = _server.where((m) => !m.fromAdmin).length;
    final nowIncoming = list.where((m) => !m.fromAdmin).length;
    _server = list;
    final echoed = {
      for (final m in list)
        if (m.clientId != null) m.clientId!,
    };
    _pending.removeWhere((p) => p.status != MsgStatus.failed && echoed.contains(p.clientId));
    if (loaded && nowIncoming > prevIncoming && !atBottom) {
      newWhileAway += nowIncoming - prevIncoming;
    }
    loaded = true;
    notifyListeners();
  }

  void setReply(ChatMessage? m) {
    replyTo = m;
    notifyListeners();
  }

  void setAtBottom(bool v) {
    if (atBottom == v) return;
    atBottom = v;
    if (v) newWhileAway = 0;
    notifyListeners();
  }

  /// Returns true if a message was started.
  bool send(String raw) {
    final text = raw.trim();
    if (text.isEmpty) return false;
    final clientId =
        '${DateTime.now().microsecondsSinceEpoch}-${math.Random().nextInt(1 << 20)}';
    final ref = replyTo == null
        ? null
        : ReplyRef(replyTo!.id, replyTo!.fromAdmin ? 'Wewe' : userName,
            replyTo!.text);
    final local = ChatMessage(
      id: 'local-$clientId',
      clientId: clientId,
      userId: userId,
      fromAdmin: true,
      text: text,
      time: DateTime.now(),
      status: MsgStatus.sending,
      replyTo: ref,
    );
    _pending.add(local);
    final replyId = replyTo?.id;
    replyTo = null;
    notifyListeners();
    _dispatch(local, replyId);
    return true;
  }

  Future<void> _dispatch(ChatMessage local, String? replyId) async {
    try {
      await repo.sendReply(
        userId: userId,
        text: local.text,
        clientId: local.clientId!,
        replyToMessageId: replyId,
      );
    } catch (_) {
      final i = _pending.indexWhere((p) => p.clientId == local.clientId);
      if (i >= 0) {
        _pending[i] = _pending[i].copyWith(status: MsgStatus.failed);
        notifyListeners();
      }
    }
  }

  void retry(ChatMessage failed) {
    final i = _pending.indexWhere((p) => p.clientId == failed.clientId);
    if (i < 0) return;
    _pending[i] = _pending[i].copyWith(status: MsgStatus.sending);
    notifyListeners();
    _dispatch(_pending[i], failed.replyTo?.messageId);
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }
}

// ----------------------------------------------------------------------------
// Chat page
// ----------------------------------------------------------------------------
class MaoniChatPage extends StatefulWidget {
  final MaoniRepository repo;
  final Conversation conversation;

  /// Called when the call button is tapped (use url_launcher in your app).
  final void Function(String phone)? onCall;

  const MaoniChatPage({
    super.key,
    required this.repo,
    required this.conversation,
    this.onCall,
  });

  @override
  State<MaoniChatPage> createState() => _MaoniChatPageState();
}

class _MaoniChatPageState extends State<MaoniChatPage> {
  late final ChatController _ctrl;
  final _scroll = ScrollController();
  final _input = TextEditingController();
  final _focus = FocusNode();
  int _lastCount = 0;
  bool _lastWasMine = false;

  @override
  void initState() {
    super.initState();
    _ctrl = ChatController(
      repo: widget.repo,
      userId: widget.conversation.userId,
      userName: widget.conversation.name,
    )..addListener(_onChanged);
    _scroll.addListener(() {
      // list is reversed: offset 0 = newest message at the bottom
      _ctrl.setAtBottom(_scroll.hasClients && _scroll.offset < 80);
    });
    _input.addListener(() => setState(() {}));
  }

  void _onChanged() {
    // The list is reversed (newest at offset 0). When the user is already at
    // the bottom, a new incoming message simply appears there and stays
    // visible. When the user scrolled up, we do NOT yank the view: a
    // "new messages" button appears instead (see ChatController.newWhileAway).
    if (mounted) setState(() {});
  }

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scroll.hasClients) {
        _scroll.animateTo(0,
            duration: const Duration(milliseconds: 250),
            curve: Curves.easeOut);
      }
    });
  }

  void _send() {
    if (_ctrl.send(_input.text)) {
      _input.clear();
      _scrollToBottom();
    }
  }

  @override
  void dispose() {
    _ctrl.removeListener(_onChanged);
    _ctrl.dispose();
    _scroll.dispose();
    _input.dispose();
    _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final c = widget.conversation;
    final entries = _entries(_ctrl.messages);
    final hasText = _input.text.trim().isNotEmpty;

    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Column(
          children: [
            _topBar(c),
            Expanded(
              child: Stack(
                children: [
                  ListView.builder(
                    controller: _scroll,
                    reverse: true,
                    padding: const EdgeInsets.fromLTRB(12, 6, 12, 12),
                    itemCount: entries.length,
                    itemBuilder: (_, i) =>
                        _entryWidget(entries[entries.length - 1 - i], c),
                  ),
                  if (!_ctrl.atBottom)
                    Positioned(
                      right: 14,
                      bottom: 12,
                      child: _Press(
                        onTap: _scrollToBottom,
                        child: Stack(
                          clipBehavior: Clip.none,
                          children: [
                            Container(
                              width: 44,
                              height: 44,
                              decoration: BoxDecoration(
                                color: Colors.white,
                                shape: BoxShape.circle,
                                border: Border.all(color: _C.border),
                                boxShadow: const [
                                  BoxShadow(
                                      color: Color(0x1A141A26),
                                      blurRadius: 8,
                                      offset: Offset(0, 2))
                                ],
                              ),
                              child: const Icon(TablerIcons.chevron_down,
                                  size: 22, color: _C.ink),
                            ),
                            if (_ctrl.newWhileAway > 0)
                              Positioned(
                                top: -6,
                                right: -4,
                                child: _CountBadge(_ctrl.newWhileAway,
                                    border: true),
                              ),
                          ],
                        ),
                      ),
                    ),
                ],
              ),
            ),
            if (_ctrl.replyTo != null) _replyPreview(c),
            _inputBar(hasText),
          ],
        ),
      ),
    );
  }

  // ---- Top bar --------------------------------------------------------------
  Widget _topBar(Conversation c) => Container(
        padding: const EdgeInsets.fromLTRB(4, 8, 4, 8),
        decoration: const BoxDecoration(
          color: Colors.white,
          border: Border(bottom: BorderSide(color: _C.line)),
        ),
        child: Row(
          children: [
            _IconBtn(TablerIcons.arrow_left, () => Navigator.of(context).pop()),
            _Avatar(c.name, size: 42, fontSize: 17),
            const SizedBox(width: 10),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(c.name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                          color: _C.ink)),
                  Text(c.phone,
                      style:
                          const TextStyle(fontSize: 12.5, color: _C.muted2)),
                ],
              ),
            ),
            _IconBtn(TablerIcons.phone, () => widget.onCall?.call(c.phone)),
            PopupMenuButton<String>(
              icon: const Icon(TablerIcons.dots_vertical,
                  size: 22, color: _C.ink),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(14)),
              color: Colors.white,
              onSelected: (v) async {
                if (v == 'delete') await _confirmDelete(c);
              },
              itemBuilder: (_) => const [
                PopupMenuItem(
                  value: 'delete',
                  child: Row(
                    children: [
                      Icon(TablerIcons.trash, size: 20, color: _C.red),
                      SizedBox(width: 10),
                      Text('Futa mazungumzo',
                          style: TextStyle(fontSize: 14.5, color: _C.red)),
                    ],
                  ),
                ),
              ],
            ),
          ],
        ),
      );

  Future<void> _confirmDelete(Conversation c) async {
    final ok = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: Colors.white,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Text('Futa mazungumzo?',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.w500)),
        content: Text('Mazungumzo yote na ${c.name} yatafutwa.',
            style: const TextStyle(fontSize: 14.5, color: _C.muted)),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(ctx, false),
              child: const Text('Hapana')),
          TextButton(
              onPressed: () => Navigator.pop(ctx, true),
              child: const Text('Futa', style: TextStyle(color: _C.red))),
        ],
      ),
    );
    if (ok == true) {
      await widget.repo.deleteConversation(c.userId);
      if (mounted) Navigator.of(context).pop();
    }
  }

  // ---- Entries (day chips + messages) --------------------------------------
  List<_Entry> _entries(List<ChatMessage> msgs) {
    final out = <_Entry>[];
    DateTime? day;
    bool? prevFromAdmin;
    for (final m in msgs) {
      final d = DateTime(m.time.year, m.time.month, m.time.day);
      if (day != d) {
        out.add(_Entry.day(d));
        day = d;
        prevFromAdmin = null;
      }
      out.add(_Entry.msg(m, gap: prevFromAdmin != null && prevFromAdmin != m.fromAdmin));
      prevFromAdmin = m.fromAdmin;
    }
    return out;
  }

  Widget _entryWidget(_Entry e, Conversation c) {
    if (e.message == null) {
      return Padding(
        padding: const EdgeInsets.only(top: 2, bottom: 8),
        child: Column(
          children: [
            Center(
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                decoration: BoxDecoration(
                  color: _C.field,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(_dayLabel(e.day!),
                    style: const TextStyle(fontSize: 12.5, color: _C.muted)),
              ),
            ),
            if (_dayLabel(e.day!) == 'Leo') ...[
              const SizedBox(height: 6),
              const Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(TablerIcons.arrow_back_up, size: 14, color: _C.hint),
                  SizedBox(width: 5),
                  Text('Telezesha ujumbe kulia ili kuujibu',
                      style: TextStyle(fontSize: 12, color: _C.hint)),
                ],
              ),
            ],
          ],
        ),
      );
    }
    final m = e.message!;
    return Padding(
      padding: EdgeInsets.only(top: e.gap ? 7 : 3),
      child: _SwipeToReply(
        onReply: () {
          _ctrl.setReply(m);
          _focus.requestFocus();
        },
        child: _Bubble(
          message: m,
          userName: c.name,
          onRetry: () => _ctrl.retry(m),
        ),
      ),
    );
  }

  // ---- Reply preview + input -----------------------------------------------
  Widget _replyPreview(Conversation c) {
    final r = _ctrl.replyTo!;
    return Container(
      margin: const EdgeInsets.fromLTRB(10, 0, 10, 0),
      decoration: const BoxDecoration(
        color: _C.replyBar,
        borderRadius: BorderRadius.vertical(top: Radius.circular(12)),
      ),
      child: IntrinsicHeight(
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Container(
              width: 4,
              decoration: const BoxDecoration(
                color: _C.green,
                borderRadius:
                    BorderRadius.only(topLeft: Radius.circular(12)),
              ),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(r.fromAdmin ? 'Wewe' : c.name,
                        style: const TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w500,
                            color: _C.quoteName)),
                    Text(r.text,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: const TextStyle(
                            fontSize: 14, color: Color(0xFF6A7280))),
                  ],
                ),
              ),
            ),
            GestureDetector(
              onTap: () => _ctrl.setReply(null),
              child: const Padding(
                padding: EdgeInsets.symmetric(horizontal: 12),
                child: Icon(TablerIcons.x, size: 20, color: _C.muted2),
              ),
            ),
          ],
        ),
      ),
    );
  }

  // Textbox ya kutuma message — kama WhatsApp: emoji kushoto ndani ya
  // uga mweupe, paperclip + camera nje kulia, kitufe cha duara cha kutuma.
  Widget _inputBar(bool hasText) => Container(
        color: Colors.white,
        padding: const EdgeInsets.fromLTRB(8, 8, 8, 10),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Expanded(
              child: Container(
                constraints: const BoxConstraints(minHeight: 46),
                padding: const EdgeInsets.symmetric(horizontal: 10),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(24),
                  border: Border.all(color: _C.border),
                ),
                child: Row(
                  children: [
                    const Icon(TablerIcons.mood_smile,
                        size: 24, color: _C.muted2),
                    Expanded(
                      child: TextField(
                        controller: _input,
                        focusNode: _focus,
                        minLines: 1,
                        maxLines: 5,
                        textInputAction: TextInputAction.newline,
                        style: const TextStyle(fontSize: 15.5, color: _C.ink),
                        decoration: const InputDecoration(
                          hintText: 'Andika jibu lako hapa...',
                          hintStyle: TextStyle(
                              color: Color(0xFF8A94A6), fontSize: 15.5),
                          border: InputBorder.none,
                          isDense: true,
                          contentPadding:
                              EdgeInsets.symmetric(horizontal: 8, vertical: 13),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(width: 10),
            const Icon(TablerIcons.paperclip, size: 23, color: _C.muted2),
            const SizedBox(width: 12),
            const Icon(TablerIcons.camera, size: 24, color: _C.muted2),
            const SizedBox(width: 10),
            _Press(
              onTap: hasText ? _send : null,
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 150),
                width: 46,
                height: 46,
                decoration: BoxDecoration(
                  color: hasText ? _C.green : _C.sendOff,
                  shape: BoxShape.circle,
                ),
                child:
                    const Icon(TablerIcons.send, size: 21, color: Colors.white),
              ),
            ),
          ],
        ),
      );
}

class _Entry {
  final DateTime? day;
  final ChatMessage? message;
  final bool gap;
  _Entry.day(this.day)
      : message = null,
        gap = false;
  _Entry.msg(this.message, {required this.gap}) : day = null;
}

// ----------------------------------------------------------------------------
// Bubble
// ----------------------------------------------------------------------------
class _Bubble extends StatelessWidget {
  final ChatMessage message;
  final String userName;
  final VoidCallback onRetry;
  const _Bubble(
      {required this.message, required this.userName, required this.onRetry});

  @override
  Widget build(BuildContext context) {
    final m = message;
    final out = m.fromAdmin;
    final maxW = MediaQuery.of(context).size.width * .8;
    final time = _hm(m.time);

    final bubble = ConstrainedBox(
      constraints: BoxConstraints(maxWidth: maxW),
      child: Container(
        padding: const EdgeInsets.fromLTRB(11, 8, 11, 6),
        decoration: BoxDecoration(
          // Nyeupe KABISA (kama WhatsApp): incoming ni nyeupe yenye mstari
          // mwembamba + kivuli kidogo ili ionekane kwenye background nyeupe.
          color: out ? _C.greenBg : Colors.white,
          border: out ? null : Border.all(color: _C.border),
          boxShadow: out
              ? null
              : const [
                  BoxShadow(
                      color: Color(0x16141414),
                      blurRadius: 5,
                      offset: Offset(0, 1)),
                ],
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(out ? 16 : 5),
            topRight: Radius.circular(out ? 5 : 16),
            bottomLeft: const Radius.circular(16),
            bottomRight: const Radius.circular(16),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            if (m.replyTo != null) _quote(m.replyTo!, out),
            Stack(
              children: [
                // Reserve room at the end of the last line for the time.
                Text.rich(
                  TextSpan(children: [
                    TextSpan(
                        text: m.text,
                        style: const TextStyle(
                            fontSize: 15.5, height: 1.4, color: _C.ink)),
                    WidgetSpan(
                        child: SizedBox(width: out ? 74 : 46, height: 1)),
                  ]),
                ),
                Positioned(
                  right: 0,
                  bottom: 0,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(time,
                          style: const TextStyle(
                              fontSize: 11.5, color: _C.muted2)),
                      if (out) ...[
                        const SizedBox(width: 3),
                        _Ticks(m.status, size: 16),
                      ],
                    ],
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );

    return Row(
      mainAxisAlignment: out ? MainAxisAlignment.end : MainAxisAlignment.start,
      children: [
        Flexible(
          child: m.status == MsgStatus.failed
              ? GestureDetector(onTap: onRetry, child: bubble)
              : bubble,
        ),
      ],
    );
  }

  Widget _quote(ReplyRef r, bool out) => Container(
        margin: const EdgeInsets.only(bottom: 6),
        decoration: BoxDecoration(
          color: out ? _C.quoteOut : _C.quoteIn,
          borderRadius: BorderRadius.circular(10),
        ),
        child: IntrinsicHeight(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Container(
                width: 3.5,
                decoration: BoxDecoration(
                  color: out ? _C.green : _C.quoteName,
                  borderRadius: const BorderRadius.horizontal(
                      left: Radius.circular(10)),
                ),
              ),
              Flexible(
                child: Padding(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 9, vertical: 6),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(r.senderName,
                          style: TextStyle(
                              fontSize: 12.5,
                              fontWeight: FontWeight.w500,
                              color: out ? _C.greenFg : _C.quoteName)),
                      Text(r.text,
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(
                              fontSize: 13.5, color: Color(0xFF6A7280))),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      );
}

// ----------------------------------------------------------------------------
// Swipe-to-reply (drag a message to the right, like WhatsApp)
// ----------------------------------------------------------------------------
class _SwipeToReply extends StatefulWidget {
  final Widget child;
  final VoidCallback onReply;
  const _SwipeToReply({required this.child, required this.onReply});

  @override
  State<_SwipeToReply> createState() => _SwipeToReplyState();
}

class _SwipeToReplyState extends State<_SwipeToReply>
    with SingleTickerProviderStateMixin {
  static const _max = 84.0;
  static const _trigger = 60.0;

  double _dx = 0;
  double _from = 0;
  bool _fired = false;
  // AnimationController inaundwa kwenye initState (SIYO late field) —
  // kuunda ticker wakati wa dispose (late field isiyowahi kutumika) kunasoma
  // ancestor ya widget iliyo-deactivated —Flutter inakataza (debug assertion).
  late final AnimationController _back;

  @override
  void initState() {
    super.initState();
    _back = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 200),
    )..addListener(() {
        setState(
            () => _dx = _from * (1 - Curves.easeOut.transform(_back.value)));
      });
  }

  @override
  void dispose() {
    _back.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final p = (_dx / _trigger).clamp(0.0, 1.0);
    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      onHorizontalDragStart: (_) => _back.stop(),
      onHorizontalDragUpdate: (d) {
        setState(() => _dx = (_dx + d.delta.dx).clamp(0.0, _max));
        if (_dx >= _trigger && !_fired) {
          _fired = true;
          HapticFeedback.lightImpact();
        }
      },
      onHorizontalDragEnd: (_) {
        if (_fired) widget.onReply();
        _fired = false;
        _from = _dx;
        _back.forward(from: 0);
      },
      child: SizedBox(
        width: double.infinity,
        child: Stack(
          children: [
            Positioned(
              left: 4,
              top: 0,
              bottom: 0,
              child: Center(
                child: Opacity(
                  opacity: p,
                  child: Transform.scale(
                    scale: .6 + p * .4,
                    child: Container(
                      width: 32,
                      height: 32,
                      decoration: const BoxDecoration(
                          color: _C.replyIconBg, shape: BoxShape.circle),
                      child: const Icon(TablerIcons.arrow_back_up,
                          size: 18, color: _C.chipText),
                    ),
                  ),
                ),
              ),
            ),
            Transform.translate(offset: Offset(_dx, 0), child: widget.child),
          ],
        ),
      ),
    );
  }
}

// ----------------------------------------------------------------------------
// Small shared widgets
// ----------------------------------------------------------------------------
class _Avatar extends StatelessWidget {
  final String name;
  final double size;
  final double fontSize;
  const _Avatar(this.name, {required this.size, required this.fontSize});

  @override
  Widget build(BuildContext context) => Container(
        width: size,
        height: size,
        alignment: Alignment.center,
        decoration:
            const BoxDecoration(color: _C.avatarBg, shape: BoxShape.circle),
        child: Text(_initial(name),
            style: TextStyle(
                fontSize: fontSize,
                fontWeight: FontWeight.w500,
                color: _C.ink)),
      );
}

class _CountBadge extends StatelessWidget {
  final int n;
  final bool border;
  const _CountBadge(this.n, {this.border = false});

  @override
  Widget build(BuildContext context) => Container(
        constraints: BoxConstraints(minWidth: border ? 20 : 22),
        height: border ? 20 : 22,
        padding: const EdgeInsets.symmetric(horizontal: 5),
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: _C.green,
          borderRadius: BorderRadius.circular(11),
          border: border ? Border.all(color: Colors.white, width: 2) : null,
        ),
        child: Text(n > 99 ? '99+' : '$n',
            style: const TextStyle(
                fontSize: 12.5, fontWeight: FontWeight.w500, color: Colors.white)),
      );
}

class _Ticks extends StatelessWidget {
  final MsgStatus status;
  final double size;
  const _Ticks(this.status, {required this.size});

  @override
  Widget build(BuildContext context) {
    switch (status) {
      case MsgStatus.sending:
        return Icon(TablerIcons.clock, size: size - 2, color: _C.tick);
      case MsgStatus.sent:
        return Icon(TablerIcons.check, size: size, color: _C.tick);
      case MsgStatus.delivered:
        return Icon(TablerIcons.checks, size: size, color: _C.tick);
      case MsgStatus.read:
        return Icon(TablerIcons.checks, size: size, color: _C.green);
      case MsgStatus.failed:
        return Icon(TablerIcons.alert_circle, size: size, color: _C.red);
    }
  }
}

class _IconBtn extends StatelessWidget {
  final IconData icon;
  final VoidCallback onTap;
  const _IconBtn(this.icon, this.onTap);

  @override
  Widget build(BuildContext context) => IconButton(
        onPressed: onTap,
        icon: Icon(icon, size: 22, color: _C.ink),
        splashRadius: 22,
      );
}

/// Press animation: scales to 0.92 while pressed.
class _Press extends StatefulWidget {
  final Widget child;
  final VoidCallback? onTap;
  const _Press({required this.child, required this.onTap});

  @override
  State<_Press> createState() => _PressState();
}

class _PressState extends State<_Press> {
  bool _down = false;

  @override
  Widget build(BuildContext context) => GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTapDown: widget.onTap == null ? null : (_) => setState(() => _down = true),
        onTapUp: widget.onTap == null ? null : (_) => setState(() => _down = false),
        onTapCancel: widget.onTap == null ? null : () => setState(() => _down = false),
        onTap: widget.onTap,
        child: AnimatedScale(
          scale: _down ? .92 : 1,
          duration: const Duration(milliseconds: 120),
          child: widget.child,
        ),
      );
}

// ----------------------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------------------
String _initial(String name) =>
    name.trim().isEmpty ? '?' : name.trim()[0].toUpperCase();

String _firstName(String name) {
  final f = name.trim().split(RegExp(r'\s+')).first;
  if (f.isEmpty) return name;
  return f[0].toUpperCase() + f.substring(1).toLowerCase();
}

String _two(int n) => n.toString().padLeft(2, '0');
String _hm(DateTime t) => '${_two(t.hour)}:${_two(t.minute)}';

const _weekdays = [
  'Jumatatu', 'Jumanne', 'Jumatano', 'Alhamisi', 'Ijumaa', 'Jumamosi', 'Jumapili'
];
const _months = [
  'Jan', 'Feb', 'Mac', 'Apr', 'Mei', 'Jun', 'Jul', 'Ago', 'Sep', 'Okt', 'Nov', 'Des'
];

int _daysAgo(DateTime t) {
  final now = DateTime.now();
  final a = DateTime(now.year, now.month, now.day);
  final b = DateTime(t.year, t.month, t.day);
  return a.difference(b).inDays;
}

/// Inbox row time: today -> HH:mm, yesterday -> Jana, this week -> weekday.
String _listTime(DateTime t) {
  final d = _daysAgo(t);
  if (d <= 0) return _hm(t);
  if (d == 1) return 'Jana';
  if (d < 7) return _weekdays[t.weekday - 1];
  return '${_two(t.day)}/${_two(t.month)}/${t.year}';
}

/// Chat day chip: Leo / Jana / 12 Okt 2026.
String _dayLabel(DateTime d) {
  final n = _daysAgo(d);
  if (n <= 0) return 'Leo';
  if (n == 1) return 'Jana';
  return '${d.day} ${_months[d.month - 1]} ${d.year}';
}

// ----------------------------------------------------------------------------
// DEMO repository (in memory). Replace with your real backend implementation.
// ----------------------------------------------------------------------------
class InMemoryMaoniRepository implements MaoniRepository {
  InMemoryMaoniRepository();

  final Map<String, ({String name, String phone})> _people = {};
  final Map<String, List<ChatMessage>> _msgs = {};
  final _changed = StreamController<String>.broadcast();
  int _n = 0;

  /// Same scenario as the approved mockup.
  factory InMemoryMaoniRepository.demo() {
    final r = InMemoryMaoniRepository();
    final now = DateTime.now();
    DateTime ago(int min) => now.subtract(Duration(minutes: min));
    DateTime days(int d) => now.subtract(Duration(days: d));

    r._add('u1', 'Godwin Wangwe Richard', '+255612500600', [
      (false, 'sawa', ago(180)),
      (false, 'naomba kujua jisi ya kutumia', ago(179)),
    ]);
    r._add('u2', 'SELEMANI HAMISI NDWATA', '+255762510826', [
      (false, 'Habari', ago(190)),
      (true, 'Kwema', ago(185)),
    ]);
    r._add('u3', 'MKASA NYABUKI MAGESA', '+255744000111', [
      (false, 'nimelipia lakini sijaona', days(1)),
      (true, 'ndio ndugu unaweza kuona wale uliolipa', days(1)),
    ]);
    r._add('u4', 'RASULI ALLY', '+255787848197', [
      (false, 'Sawa', days(3)),
      (true, 'ok', days(3)),
    ]);
    return r;
  }

  void _add(String id, String name, String phone,
      List<(bool, String, DateTime)> items) {
    _people[id] = (name: name, phone: phone);
    _msgs[id] = [
      for (final it in items)
        ChatMessage(
          id: 'm${_n++}',
          userId: id,
          fromAdmin: it.$1,
          text: it.$2,
          time: it.$3,
          status: it.$1 ? MsgStatus.read : MsgStatus.delivered,
        ),
    ];
  }

  /// For testing the live updates: pretend the person sent a message.
  void simulateIncoming(String userId, String text) {
    _msgs[userId]!.add(ChatMessage(
      id: 'm${_n++}',
      userId: userId,
      fromAdmin: false,
      text: text,
      time: DateTime.now(),
    ));
    _changed.add(userId);
  }

  List<Conversation> _conversations() {
    final list = <Conversation>[];
    _msgs.forEach((id, msgs) {
      if (msgs.isEmpty) return;
      final last = msgs.last;
      var awaiting = 0;
      for (var i = msgs.length - 1; i >= 0 && !msgs[i].fromAdmin; i--) {
        awaiting++;
      }
      list.add(Conversation(
        userId: id,
        name: _people[id]!.name,
        phone: _people[id]!.phone,
        lastText: last.text,
        lastTime: last.time,
        lastFromAdmin: last.fromAdmin,
        lastStatus: last.status,
        awaiting: awaiting,
      ));
    });
    list.sort((a, b) {
      if ((a.awaiting > 0) != (b.awaiting > 0)) return a.awaiting > 0 ? -1 : 1;
      return b.lastTime.compareTo(a.lastTime);
    });
    return list;
  }

  @override
  Stream<List<Conversation>> watchConversations() async* {
    yield _conversations();
    yield* _changed.stream.map((_) => _conversations());
  }

  @override
  Stream<List<ChatMessage>> watchMessages(String userId) async* {
    yield List.of(_msgs[userId] ?? const []);
    yield* _changed.stream
        .where((id) => id == userId)
        .map((_) => List.of(_msgs[userId] ?? const []));
  }

  @override
  Future<void> sendReply({
    required String userId,
    required String text,
    required String clientId,
    String? replyToMessageId,
  }) async {
    await Future<void>.delayed(const Duration(milliseconds: 400));
    final list = _msgs[userId]!;
    ReplyRef? ref;
    if (replyToMessageId != null) {
      final target = list.where((m) => m.id == replyToMessageId);
      if (target.isNotEmpty) {
        final t = target.first;
        ref = ReplyRef(t.id, t.fromAdmin ? 'Wewe' : _people[userId]!.name, t.text);
      }
    }
    // The saved message echoes the clientId -> the app replaces its local copy.
    list.add(ChatMessage(
      id: 'm${_n++}',
      clientId: clientId,
      userId: userId,
      fromAdmin: true,
      text: text,
      time: DateTime.now(),
      status: MsgStatus.delivered,
      replyTo: ref,
    ));
    _changed.add(userId);
  }

  @override
  Future<void> deleteConversation(String userId) async {
    _msgs.remove(userId);
    _people.remove(userId);
    _changed.add(userId);
  }

  @override
  Future<void> markAllSeen() async {}
}

// ============================================================================
// INTEGRATION LAYER — API halisi ya backend (Kubadilishana / EssTransfer)
//
// Ramani ya data (GET /feedback/admin/all):
//   feedback item → mazungumzo moja kwa MTU (RULE 1):
//     key (userId) = user_phone (au user_id kama simu haipo)
//     jina  = user_name (au user_phone kama jina hakipo)
//     msg ya mtumiaji = "subject\nmessage"  @created_at
//     msg ya admin    = admin_reply          @admin_replied_at
//                       + quote ya ujumbe wa mtumiaji (kama WhatsApp)
//
//   sendReply  → POST /feedback/admin/{id}/reply
//                (id = feedback ya ujumbe unaojibu; bila quote = ile isiyojibiwa
//                 ya mwisho ya mtumiaji huyo)
//   delete     → DELETE /feedback/admin/{id} kwa kila feedback ya mtumiaji huyo
//   LIVE       → WS 'notification' (feedback.new / feedback.replied) + timer 30s
//
//  CLIENTID ECHO: backend ya sasa hairudishi clientId. Repository hii
//  ina-"fake echo": jibu lililohifadhiwa linalinganishwa na copy ya local
//  kwa (userId + maandishi + muda), kisha clientId inabandikwa — hivyo
//  ChatController inaondoa copy ya local NA UJUMBE HAIONEKANI MARA MBILI.
// ============================================================================

DateTime _parseIso(dynamic iso, [DateTime? fallback]) {
  final s = iso?.toString() ?? '';
  if (s.isEmpty) return fallback ?? DateTime.now();
  try {
    return DateTime.parse(s).toLocal();
  } catch (_) {
    return fallback ?? DateTime.now();
  }
}

/// Jina la mtu kwenye orodha (jina halisi, la simu kama hakijulikani).
String _displayName(Map<String, dynamic> m) {
  final name = (m['user_name'] ?? m['full_name'] ?? '').toString().trim();
  if (name.isNotEmpty && !name.startsWith('+')) return name;
  final p = (m['user_phone'] ?? m['phone'] ?? '').toString().trim();
  return p.isNotEmpty ? p : 'Mtumiaji';
}

/// Ujumbe wa mtumiaji: subject + message (kama zipo zote mbili).
String _userText(Map<String, dynamic> m) {
  final subject = (m['subject'] ?? '').toString().trim();
  final message = (m['message'] ?? '').toString().trim();
  return [
    if (subject.isNotEmpty) subject,
    if (message.isNotEmpty) message,
  ].join('\n');
}

/// Jibu la admin: admin_reply (au reply kama ni String/Map yenye text).
String _replyText(Map<String, dynamic> m) {
  final a = (m['admin_reply'] ?? '').toString().trim();
  if (a.isNotEmpty) return a;
  final r = m['reply'];
  if (r is Map) {
    final rm = Map<String, dynamic>.from(r);
    return (rm['text'] ?? rm['message'] ?? '').toString().trim();
  }
  return (r ?? '').toString().trim();
}

/// Ufunguo wa mazungumzo (userId): simu ya mtumiaji, au id kama hakuna simu.
String _feedbackKey(Map<String, dynamic> m) {
  final p = (m['user_phone'] ?? m['phone'] ?? '').toString().trim();
  if (p.isNotEmpty) return p;
  return (m['user_id'] ?? m['_id'] ?? m['id'] ?? '').toString();
}

/// Jibu lililotumwa tukio la local — linasubiri kulinganishwa na server copy
/// (fake echo ya clientId, angalia maelezo hapo juu).
class _SentEcho {
  final String clientId;
  final String userId;
  final String text;
  final DateTime sentAt;
  bool matched = false;
  _SentEcho(this.clientId, this.userId, this.text, this.sentAt);
}

class ApiMaoniRepository implements MaoniRepository {
  ApiMaoniRepository._() {
    WebSocketService().on('notification', _onWs);
  }

  static final ApiMaoniRepository instance = ApiMaoniRepository._();

  List<Map<String, dynamic>> _items = const [];
  bool _loading = false;
  final _updates = StreamController<void>.broadcast();
  Timer? _timer;
  final List<_SentEcho> _sent = [];

  /// WS LIVE: maoni mpya / majibu mapya → refresh ya moja kwa moja.
  void _onWs(Map<String, dynamic> payload) {
    final type = (payload['type'] ?? payload['event'])?.toString() ?? '';
    if (type == 'feedback.new' || type == 'feedback.replied') refresh();
  }

  void _ensureTimer() {
    _timer ??= Timer.periodic(const Duration(seconds: 30), (_) => refresh());
  }

  /// LETA data mpya kutoka backend. Kimya kama imeshindikana (tunabakisha
  /// data ya zamani); matumizi ya kwanza huleta spinner kwenye inbox.
  Future<void> refresh({bool force = false}) async {
    if (!force && (_loading || !_updates.hasListener)) return;
    _loading = true;
    try {
      final res = await ApiService().adminListFeedback(status: '', q: '');
      final data = res.data;
      final list = data is List
          ? data
          : (data is Map
              ? (data['items'] as List? ?? data['results'] as List? ?? const [])
              : const []);
      _items = [
        for (final it in list)
          if (it is Map) Map<String, dynamic>.from(it),
      ];
      if (!_updates.isClosed) _updates.add(null);
    } catch (_) {
      // refresh ya nyuma ya pazia — data ya zamani inaendelea kuonekana
    } finally {
      _loading = false;
    }
  }

  // ---- Streams -------------------------------------------------------------

  @override
  Stream<List<Conversation>> watchConversations() async* {
    _ensureTimer();
    unawaited(refresh());
    yield _conversations();
    await for (final _ in _updates.stream) {
      yield _conversations();
    }
  }

  @override
  Stream<List<ChatMessage>> watchMessages(String userId) async* {
    _ensureTimer();
    unawaited(refresh());
    yield _messagesFor(userId);
    await for (final _ in _updates.stream) {
      yield _messagesFor(userId);
    }
  }

  // ---- Ramani: items → ChatMessage / Conversation ---------------------------

  List<ChatMessage> _messagesFor(String userId) {
    final out = <ChatMessage>[];
    final items = _items.where((m) => _feedbackKey(m) == userId).toList()
      ..sort((a, b) =>
          _parseIso(a['created_at']).compareTo(_parseIso(b['created_at'])));
    for (final m in items) {
      final id = (m['id'] ?? m['_id'] ?? '').toString();
      final created = _parseIso(m['created_at']);
      final userText = _userText(m);
      if (userText.isNotEmpty) {
        out.add(ChatMessage(
          id: '${id}u',
          userId: userId,
          fromAdmin: false,
          text: userText,
          time: created,
          status: MsgStatus.delivered,
        ));
      }
      final reply = _replyText(m);
      if (reply.isNotEmpty) {
        out.add(ChatMessage(
          id: '${id}r',
          userId: userId,
          fromAdmin: true,
          text: reply,
          time: _parseIso(m['admin_replied_at'] ?? m['replied_at'], created),
          status: MsgStatus.delivered,
          replyTo:
              userText.isEmpty ? null : ReplyRef('${id}u', _displayName(m), userText),
        ));
      }
    }
    _applyEchoes(out, userId);
    out.sort((a, b) => a.time.compareTo(b.time));
    return out;
  }

  /// Fake echo: jibu la server lenye maandishi sawa (na muda uleile) linapata
  /// clientId ya local — ChatController inaondoa copy ya local (RULE 2).
  void _applyEchoes(List<ChatMessage> msgs, String userId) {
    for (final e in _sent) {
      if (e.matched || e.userId != userId) continue;
      for (var i = msgs.length - 1; i >= 0; i--) {
        final m = msgs[i];
        final inWindow =
            !m.time.isBefore(e.sentAt.subtract(const Duration(minutes: 5)));
        if (m.fromAdmin &&
            m.clientId == null &&
            m.text == e.text &&
            inWindow) {
          e.matched = true;
          msgs[i] = ChatMessage(
            id: m.id,
            clientId: e.clientId,
            userId: m.userId,
            fromAdmin: m.fromAdmin,
            text: m.text,
            time: m.time,
            status: m.status,
            replyTo: m.replyTo,
          );
          break;
        }
      }
    }
  }

  List<Conversation> _conversations() {
    final byKey = <String, List<Map<String, dynamic>>>{};
    for (final m in _items) {
      byKey.putIfAbsent(_feedbackKey(m), () => []).add(m);
    }
    final list = <Conversation>[];
    byKey.forEach((key, items) {
      final msgs = _messagesFor(key);
      if (msgs.isEmpty) return;
      final last = msgs.last;
      var awaiting = 0;
      for (var i = msgs.length - 1; i >= 0 && !msgs[i].fromAdmin; i--) {
        awaiting++;
      }
      final first = items.first;
      list.add(Conversation(
        userId: key,
        name: _displayName(first),
        phone: (first['user_phone'] ?? first['phone'] ?? '').toString(),
        lastText: last.text,
        lastTime: last.time,
        lastFromAdmin: last.fromAdmin,
        lastStatus: last.fromAdmin ? last.status : MsgStatus.delivered,
        awaiting: awaiting,
      ));
    });
    list.sort((a, b) {
      if ((a.awaiting > 0) != (b.awaiting > 0)) return a.awaiting > 0 ? -1 : 1;
      return b.lastTime.compareTo(a.lastTime);
    });
    return list;
  }

  // ---- Write operations ----------------------------------------------------

  @override
  Future<void> sendReply({
    required String userId,
    required String text,
    required String clientId,
    String? replyToMessageId,
  }) async {
    // Chagua feedback ya kujibu: ile ya ujumbe unaoujibu (quote), la sivyo
    // ile ya mwisho ya mtumiaji huyo ISIVOJIBIWA, la sivyo ya mwisho kabisa.
    String feedbackId;
    final quotedId = replyToMessageId ?? '';
    if (quotedId.endsWith('u') && quotedId.length > 1) {
      feedbackId = quotedId.substring(0, quotedId.length - 1);
    } else {
      final items = _items.where((m) => _feedbackKey(m) == userId).toList()
        ..sort((a, b) =>
            _parseIso(b['created_at']).compareTo(_parseIso(a['created_at'])));
      String? picked;
      for (final m in items) {
        if (_replyText(m).isEmpty) {
          picked = (m['id'] ?? m['_id'] ?? '').toString();
          break;
        }
      }
      picked ??= items.isNotEmpty
          ? (items.first['id'] ?? items.first['_id'] ?? '').toString()
          : '';
      feedbackId = picked;
    }
    if (feedbackId.isEmpty) {
      throw Exception('Hakuna maoni ya kujibu');
    }

    _sent.add(_SentEcho(clientId, userId, text, DateTime.now()));
    try {
      await ApiService().adminReplyFeedback(feedbackId, text);
      await refresh(force: true);
    } catch (_) {
      rethrow; // ChatController inaonyesha "failed" + kitufe cha kujaribu tena
    }
  }

  @override
  Future<void> deleteConversation(String userId) async {
    final ids = [
      for (final m in _items)
        if (_feedbackKey(m) == userId) (m['id'] ?? m['_id'] ?? '').toString(),
    ].where((s) => s.isNotEmpty).toList();
    if (ids.isEmpty) return;
    for (final id in ids) {
      try {
        await ApiService().adminDeleteFeedback(id);
      } catch (e) {
        AppToast.error(friendlyError(e));
        unawaited(refresh(force: true));
        return;
      }
    }
    _sent.removeWhere((e) => e.userId == userId);
    await refresh(force: true);
  }

  @override
  Future<void> markAllSeen() async {
    // Badge ya shell inafutwa na AdminBadgeService baada ya kujibu tu —
    // kitufe hiki ni no-op kwenye backend ya sasa.
  }
}

// ----------------------------------------------------------------------------
// Ukurasa wa Maoni kwenye AdminShell (nav index 8) — repo ya API halisi.
// MaoniInboxPage ni BODY tu: shell ina top bar, drawer na bottom navigation.
// ----------------------------------------------------------------------------
class AdminMaoniPage extends StatelessWidget {
  const AdminMaoniPage({super.key});

  Future<void> _call(String phone) async {
    final digits = phone.replaceAll(RegExp(r'\D'), '');
    try {
      await launchUrl(Uri.parse('tel:$digits'),
          mode: LaunchMode.externalApplication);
    } catch (_) {
      AppToast.error('Imeshindikana kufungua');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaoniInboxPage(repo: ApiMaoniRepository.instance, onCall: _call);
  }
}
